### ISSUE TITLE
Request about hud

### ISSUE THREAD

**Issue by mrPassion78** [900hasse/FS22_REAgui#1]
Hi there, thnx for the REA mod again.. this is what makes the game so much more fun to play, so thnx a million.
1 request : would it be possible for the REA hud to stay visible even when the ingame hud ( ALT-F1 ) is blended out?

I use Sim Dashboard and i would love to be able to see the REA info, while everything else is shown on my 2 tablets with SimDash.

Or is there some i could add to the LUA script, that it would be permanently visible

**Comment by 900hasse** [comment]
Hello!

 

Just comment row 42 and 77, this should make it always visible.

 



 

//Hans

 

Från: mrPassion78 ***@***.***> 
Skickat: den 13 februari 2022 16:09
Till: 900hasse/FS22_REAgui ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [900hasse/FS22_REAgui] Request about hud (Issue #1)

 

Hi there, thnx for the REA mod again.. this is what makes the game so much more fun to play, so thnx a million.
1 request : would it be possible for the REA hud to stay visible even when the ingame hud ( ALT-F1 ) is blended out?

I use Sim Dashboard and i would love to be able to see the REA info, while everything else is shown on my 2 tablets with SimDash.

Or is there some i could add to the LUA script, that it would be permanently visible

**Comment by mrPassion78** [comment]
it worked, thnx so much.
